name: test_01_h_r
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  http: 0.13.5
  cupertino_icons: ^1.0.2
  get: 4.6.5
  intl: 0.18.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

